name: core
description: A new Flutter package project.
version: 0.0.1
homepage: eggy.as

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0-nullsafety.0

  built_collection: ^5.0.0

  # Image carousel used on landing page
  carousel_slider: ^4.0.0-nullsafety.0

  dio: ^4.0.0

  fimber: ^0.6.1 # For logging
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.0.0
  freezed_annotation: ^0.14.2

  get_it: ^7.1.3
  google_fonts: ^2.1.0
  grouped_list: ^4.0.0

  intl: ^0.17.0

  json_annotation: ^4.0.1

  kt_dart: ^0.9.1

  # can't use flutter_styled_toast as this breaks
  # the `resizeToAvoidBottomInset` on all Scaffolds
  # throughout the app
  oktoast: ^3.0.0

  path: ^1.8.0
  provider: ^5.0.0

  quiver: ^3.0.1

  # this needs to stay on 10.2.x until we can update our project to flutter > 2.2
  reactive_forms: ^10.2.0
  rxdart: ^0.27.0

  table_calendar: ^3.0.0

  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1
  json_serializable: ^4.1.2
  json_serializable_immutable_collections: ^0.7.0

  # Static analysis lint rules
  lint: ^1.5.3