name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  # so we can show the app icon based on the current build variant
  application_icon: ^2.0.0

  flutter:
    sdk: flutter

  # For interaction with AWS backend
  amplify_auth_cognito: ^0.1.5 # not null safe
  amplify_core: ^0.1.5 # not null safe
  amplify_flutter: ^0.1.5 # not null safe

  amplitude_flutter: ^3.1.0

  auto_size_text: ^3.0.0-nullsafety.0

  device_info: ^2.0.1
  dio: ^4.0.0

  core:
    path: ../core

  mime: ^1.0.0

  # Firebase related packages
  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.0

  # build and version numbers
  package_info: ^2.0.0

  # For storage of user settings
  shared_preferences: ^2.0.5

  # For caching data or files
  stash: ^2.0.2
  stash_disk: ^2.0.0-nullsafety.2
  #    git: https://github.com/yurisasc/stash_disk # Uses a forked version to support compatibility with path_provider ^2.1.0

  # For access to ios keychain and android keystore
  flutter_secure_storage: ^4.2.0

  # -- state management
  provider: ^5.0.0
  rxdart: ^0.27.0

  # Model driven forms and validation
  # this needs to stay on 10.2.x until we can update our project to flutter > 2.2
  reactive_forms: ^10.2.0

  # -- data classes
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1
  built_collection: ^5.0.0
  kt_dart: ^0.9.1

  uuid: ^3.0.4
  intl: ^0.17.0

  quiver: ^3.0.1

  # Service locator for dependency injection
  get_it: ^7.1.3

  # For logging
  fimber: ^0.6.1

  # -- widgets and ui support
  table_calendar: ^3.0.0
  grouped_list: ^4.0.0
  youtube_plyr_iframe: ^2.0.5+1

  # Allow rendering of SVG assets
  flutter_svg: ^0.22.0

  # Image carousel used on landing page
  carousel_slider: ^4.0.0-nullsafety.0

  # can't use flutter_styled_toast as this breaks
  # the `resizeToAvoidBottomInset` on all Scaffolds
  # throughout the app
  oktoast: ^3.0.0

  # Font used throughout the toast
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.0.0

  # For on-device biometric authentication
  local_auth: ^1.1.5

  # -- documents & files
  native_pdf_renderer: ^3.0.0
  path: ^1.8.0
  path_provider: ^2.0.1
  image_picker: ^0.7.5+2

  file_picker: ^3.0.1

  flutter_genius_scan: ^4.0.8

  webview_flutter: ^2.0.7

  intercom_flutter: ^3.2.0

  sentry_flutter: ^5.0.0

  receive_sharing_intent: ^1.4.5
  # For exporting life item
  share: ^2.0.1
  # pdf: ^3.2.0 # Will be needed to export images as PDFs

  url_launcher: ^6.0.3
  uni_links2: ^0.6.0+2
  wakelock: ^0.5.2

dependency_overrides:
  receive_sharing_intent:
    git:
      url: https://github.com/eggyapp/receive_sharing_intent.git

dev_dependencies:
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1
  json_serializable: ^4.1.2
  json_serializable_immutable_collections: ^0.7.0

  # Static analysis lint rules
  lint: ^1.5.3


flutter:

  uses-material-design: true
